version: '3.4'

services:
  sdcserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - sdcdb
  sdcdb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
